/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: topology.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as topology_pb from './topology_pb'; // proto import: "topology.proto"


export class TopologyServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSubscribeToDevice = new grpcWeb.MethodDescriptor(
    '/TopologyService/SubscribeToDevice',
    grpcWeb.MethodType.SERVER_STREAMING,
    topology_pb.SubscribeRequest,
    topology_pb.NetworkEvent,
    (request: topology_pb.SubscribeRequest) => {
      return request.serializeBinary();
    },
    topology_pb.NetworkEvent.deserializeBinary
  );

  subscribeToDevice(
    request: topology_pb.SubscribeRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<topology_pb.NetworkEvent> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/TopologyService/SubscribeToDevice',
      request,
      metadata || {},
      this.methodDescriptorSubscribeToDevice);
  }

  methodDescriptorToggleDevice = new grpcWeb.MethodDescriptor(
    '/TopologyService/ToggleDevice',
    grpcWeb.MethodType.UNARY,
    topology_pb.ToggleRequest,
    topology_pb.ToggleResponse,
    (request: topology_pb.ToggleRequest) => {
      return request.serializeBinary();
    },
    topology_pb.ToggleResponse.deserializeBinary
  );

  toggleDevice(
    request: topology_pb.ToggleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<topology_pb.ToggleResponse>;

  toggleDevice(
    request: topology_pb.ToggleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: topology_pb.ToggleResponse) => void): grpcWeb.ClientReadableStream<topology_pb.ToggleResponse>;

  toggleDevice(
    request: topology_pb.ToggleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: topology_pb.ToggleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/TopologyService/ToggleDevice',
        request,
        metadata || {},
        this.methodDescriptorToggleDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/TopologyService/ToggleDevice',
    request,
    metadata || {},
    this.methodDescriptorToggleDevice);
  }

}

